[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  [functions.sync-privy]
    schedule = "*/15 * * * *"

[[redirects]]
  from = "/ref/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/claim/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
